name: Build and Sync to AWS S3

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: 'build/'

      - name: Sync Build Folder to S3
        run: aws s3 sync './build' ${{secrets.AWS_S3_BUCKET}}
